apiVersion: v1
kind: ConfigMap
metadata:
  name: elevator-service-cm
data:
  springDatasourceUrl: jdbc:h2:mem:elevator
  springDatasourceUsername: sa
  springDatasourcePassword: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevator-service-app
  labels:
    app: elevator-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elevator-service-app
  template:
    metadata:
      labels:
        app: elevator-service-app
    spec:
      containers:
        - name: elevator-service-app
          image: ptyagi13/elevator-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
          env:
            - name: datasource_url
              valueFrom:
                configMapKeyRef:
                  name: elevator-service-cm
                  key: springDatasourceUrl
            - name: datasource_username
              valueFrom:
                configMapKeyRef:
                  name: elevator-service-cm
                  key: springDatasourceUsername
            - name: datasource_password
              valueFrom:
                configMapKeyRef:
                  name: elevator-service-cm
                  key: springDatasourcePassword


---
apiVersion: v1
kind: Service
metadata:
  name: elevator-service-svc
spec:
  ports:
    - targetPort: 9003
      port: 80
  selector:
    app: elevator-service-app