apiVersion: v1
kind: ConfigMap
metadata:
  name: history-service-cm
data:
  springDatasourceUrl: jdbc:h2:mem:elevator
  springDatasourceUsername: sa
  springDatasourcePassword: password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service-app
  labels:
    app: history-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service-app
  template:
    metadata:
      labels:
        app: history-service-app
    spec:
      containers:
        - name: history-service-app
          image: ptyagi13/history-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          env:
            - name: datasource_url
              valueFrom:
                configMapKeyRef:
                  name: history-service-cm
                  key: springDatasourceUrl
            - name: datasource_username
              valueFrom:
                configMapKeyRef:
                  name: history-service-cm
                  key: springDatasourceUsername
            - name: datasource_password
              valueFrom:
                configMapKeyRef:
                  name: history-service-cm
                  key: springDatasourcePassword

---
apiVersion: v1
kind: Service
metadata:
  name: history-service-svc
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: history-service-app